import type { AppSettings } from '../electron';

export const DEFAULT_SETTINGS_FALLBACK: AppSettings = {
  theme: 'paper',
  fontSize: 16,
  uiLanguage: 'en',
  defaultViewMode: 'rich',
  recentFiles: [],
  aiProviders: [
    {
      id: 'kimi',
      name: 'Kimi',
      baseUrl: 'https://api.moonshot.cn/v1',
      model: 'kimi-k2.5',
      enabled: true,
      isDefault: true,
      hasApiKey: false,
      apiKeyMasked: '',
    },
    {
      id: 'openai',
      name: 'OpenAI',
      baseUrl: 'https://api.openai.com/v1',
      model: 'gpt-4.1-mini',
      enabled: false,
      isDefault: false,
      hasApiKey: false,
      apiKeyMasked: '',
    },
  ],
  webSearch: {
    enabled: false,
    provider: 'brave',
    baseUrl: 'https://api.search.brave.com/res/v1/web/search',
    resultCount: 5,
    country: 'US',
    searchLang: 'en',
    searchEngineId: '',
    hasApiKey: false,
    apiKeyMasked: '',
  },
  aiMemory: {
    enabled: true,
  },
};

export const TOOL_PANEL_LABELS = {
  outline: 'Outline',
  info: 'Info',
  find: 'Find',
  syntax: 'Syntax',
} as const;

export const MARKDOWN_SYNTAX_HELP = [
  {
    category: 'Headings',
    items: [
      { syntax: '# Title', desc: 'H1 heading' },
      { syntax: '## Title', desc: 'H2 heading' },
      { syntax: '### Title', desc: 'H3 heading' },
      { syntax: '#### Title', desc: 'H4 heading' },
      { syntax: '##### Title', desc: 'H5 heading' },
      { syntax: '###### Title', desc: 'H6 heading' },
    ],
  },
  {
    category: 'Text',
    items: [
      { syntax: '**bold**', desc: 'Bold text' },
      { syntax: '*italic*', desc: 'Italic text' },
      { syntax: '***bold italic***', desc: 'Bold + italic' },
      { syntax: '~~strike~~', desc: 'Strikethrough' },
      { syntax: '`code`', desc: 'Inline code' },
      { syntax: '<mark>highlight</mark>', desc: 'Inline HTML highlight' },
    ],
  },
  {
    category: 'Lists',
    items: [
      { syntax: '- item', desc: 'Unordered list' },
      { syntax: '1. item', desc: 'Ordered list' },
      { syntax: '- [ ] task', desc: 'Task list' },
      { syntax: '- [x] done', desc: 'Completed task' },
      { syntax: '  - nested', desc: 'Nested list item' },
    ],
  },
  {
    category: 'Links & Media',
    items: [
      { syntax: '[label](https://example.com)', desc: 'Link' },
      { syntax: '![alt](./figure.png)', desc: 'Image' },
      { syntax: '<https://example.com>', desc: 'Autolink' },
      { syntax: '[label][ref]', desc: 'Reference link' },
      { syntax: '[ref]: https://example.com', desc: 'Reference target' },
    ],
  },
  {
    category: 'Blocks',
    items: [
      { syntax: '> quote', desc: 'Blockquote' },
      { syntax: '> nested\\n> quote', desc: 'Multi-line quote' },
      { syntax: '---', desc: 'Horizontal rule' },
      { syntax: '```ts', desc: 'Code fence' },
      { syntax: '$$...$$', desc: 'Math block' },
      { syntax: '<!-- note -->', desc: 'HTML comment' },
    ],
  },
  {
    category: 'Tables',
    items: [
      { syntax: '| A | B |', desc: 'Table header' },
      { syntax: '| --- | --- |', desc: 'Table separator' },
      { syntax: '| :-- | --: |', desc: 'Left / right alignment' },
      { syntax: '| 1 | 2 |', desc: 'Table row' },
    ],
  },
  {
    category: 'Notes',
    items: [
      { syntax: '$E = mc^2$', desc: 'Inline math' },
      { syntax: '[^1]', desc: 'Footnote ref' },
      { syntax: '[^1]: footnote', desc: 'Footnote body' },
      { syntax: '\\*escaped\\*', desc: 'Escape markdown token' },
    ],
  },
];

export const EMOJI_CATEGORIES = [
  {
    name: 'Faces',
    items: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😎',
      '🤓',
      '🥳',
      '😴',
      '🤔',
      '😭',
      '😤',
      '😱',
      '🤖',
    ],
  },
  {
    name: 'Gestures',
    items: [
      '👋',
      '🤚',
      '✋',
      '👌',
      '✌️',
      '🤞',
      '👍',
      '👎',
      '👏',
      '🙌',
      '🤝',
      '🙏',
      '☝️',
      '👇',
      '👉',
      '👈',
      '💪',
      '🫶',
    ],
  },
  {
    name: 'Symbols',
    items: [
      '❤️',
      '💛',
      '💚',
      '💙',
      '💜',
      '⭐',
      '✨',
      '🔥',
      '💯',
      '✅',
      '❌',
      '❓',
      '❗',
      '💡',
      '🎯',
      '📌',
      '📍',
      '⚠️',
      '🔒',
      '🔓',
    ],
  },
  {
    name: 'Writing',
    items: [
      '✍️',
      '📝',
      '📚',
      '📎',
      '🧠',
      '⚡️',
      '☕️',
      '🚀',
      '🌿',
      '→',
      '•',
      '★',
      '§',
      '¶',
      '†',
      '‡',
      '©',
      '®',
      '™',
    ],
  },
  {
    name: 'Arrows',
    items: ['→', '←', '↑', '↓', '↔', '↕', '⇒', '⇐', '⇔', '↗', '↘', '↙', '↖', '⟶', '⟵', '⟷'],
  },
];

export const EMOJI_CATEGORY_LABELS = {
  en: {
    Faces: 'Faces',
    Gestures: 'Gestures',
    Symbols: 'Symbols',
    Writing: 'Writing',
    Arrows: 'Arrows',
  },
  'zh-CN': {
    Faces: '表情',
    Gestures: '手势',
    Symbols: '符号',
    Writing: '写作',
    Arrows: '箭头',
  },
} as const;

export const EMOJI_LABELS = {
  en: {
    '😀': 'grinning face',
    '😃': 'smiling face',
    '😄': 'grinning face with smiling eyes',
    '😁': 'beaming face',
    '😆': 'laughing face',
    '😅': 'grinning face with sweat',
    '🤣': 'rolling on the floor laughing',
    '😂': 'face with tears of joy',
    '🙂': 'slightly smiling face',
    '😊': 'smiling face with smiling eyes',
    '😇': 'smiling face with halo',
    '🥰': 'smiling face with hearts',
    '😍': 'smiling face with heart-eyes',
    '🤩': 'star-struck',
    '😘': 'face blowing a kiss',
    '😎': 'smiling face with sunglasses',
    '🤓': 'nerd face',
    '🥳': 'partying face',
    '😴': 'sleeping face',
    '🤔': 'thinking face',
    '😭': 'loudly crying face',
    '😤': 'face with steam from nose',
    '😱': 'face screaming in fear',
    '🤖': 'robot',
    '👋': 'waving hand',
    '🤚': 'raised back of hand',
    '✋': 'raised hand',
    '👌': 'OK hand',
    '✌️': 'victory hand',
    '🤞': 'crossed fingers',
    '👍': 'thumbs up',
    '👎': 'thumbs down',
    '👏': 'clapping hands',
    '🙌': 'raising hands',
    '🤝': 'handshake',
    '🙏': 'folded hands',
    '☝️': 'index pointing up',
    '👇': 'index pointing down',
    '👉': 'index pointing right',
    '👈': 'index pointing left',
    '💪': 'flexed biceps',
    '🫶': 'heart hands',
    '❤️': 'red heart',
    '💛': 'yellow heart',
    '💚': 'green heart',
    '💙': 'blue heart',
    '💜': 'purple heart',
    '⭐': 'star',
    '✨': 'sparkles',
    '🔥': 'fire',
    '💯': 'hundred points',
    '✅': 'check mark',
    '❌': 'cross mark',
    '❓': 'question mark',
    '❗': 'exclamation mark',
    '💡': 'light bulb',
    '🎯': 'bullseye',
    '📌': 'pushpin',
    '📍': 'round pushpin',
    '⚠️': 'warning',
    '🔒': 'locked',
    '🔓': 'unlocked',
    '✍️': 'writing hand',
    '📝': 'memo',
    '📚': 'books',
    '📎': 'paperclip',
    '🧠': 'brain',
    '⚡️': 'lightning',
    '☕️': 'coffee',
    '🚀': 'rocket',
    '🌿': 'herb',
    '→': 'right arrow',
    '•': 'bullet',
    '★': 'black star',
    '§': 'section sign',
    '¶': 'pilcrow',
    '†': 'dagger',
    '‡': 'double dagger',
    '©': 'copyright',
    '®': 'registered sign',
    '™': 'trade mark',
    '←': 'left arrow',
    '↑': 'up arrow',
    '↓': 'down arrow',
    '↔': 'left-right arrow',
    '↕': 'up-down arrow',
    '⇒': 'right double arrow',
    '⇐': 'left double arrow',
    '⇔': 'left-right double arrow',
    '↗': 'up-right arrow',
    '↘': 'down-right arrow',
    '↙': 'down-left arrow',
    '↖': 'up-left arrow',
    '⟶': 'long right arrow',
    '⟵': 'long left arrow',
    '⟷': 'long left-right arrow',
  },
  'zh-CN': {
    '😀': '开心笑脸',
    '😃': '大笑',
    '😄': '咧嘴笑',
    '😁': '露齿笑',
    '😆': '眯眼大笑',
    '😅': '汗笑',
    '🤣': '笑到打滚',
    '😂': '笑哭',
    '🙂': '微笑',
    '😊': '害羞微笑',
    '😇': '天使光环',
    '🥰': '爱心笑脸',
    '😍': '花痴',
    '🤩': '星星眼',
    '😘': '飞吻',
    '😎': '墨镜笑脸',
    '🤓': '书呆子',
    '🥳': '庆祝派对',
    '😴': '睡觉',
    '🤔': '思考',
    '😭': '大哭',
    '😤': '生气喷气',
    '😱': '尖叫惊讶',
    '🤖': '机器人',
    '👋': '挥手',
    '🤚': '举手',
    '✋': '手掌',
    '👌': '没问题',
    '✌️': '胜利手势',
    '🤞': '交叉手指',
    '👍': '点赞',
    '👎': '点踩',
    '👏': '鼓掌',
    '🙌': '双手高举',
    '🤝': '握手',
    '🙏': '双手合十',
    '☝️': '向上指',
    '👇': '向下指',
    '👉': '向右指',
    '👈': '向左指',
    '💪': '肌肉',
    '🫶': '比心手势',
    '❤️': '红心',
    '💛': '黄心',
    '💚': '绿心',
    '💙': '蓝心',
    '💜': '紫心',
    '⭐': '星星',
    '✨': '闪光',
    '🔥': '火焰',
    '💯': '满分',
    '✅': '勾选',
    '❌': '叉号',
    '❓': '问号',
    '❗': '感叹号',
    '💡': '灵感灯泡',
    '🎯': '靶心',
    '📌': '图钉',
    '📍': '定位图钉',
    '⚠️': '警告',
    '🔒': '锁定',
    '🔓': '解锁',
    '✍️': '书写',
    '📝': '笔记',
    '📚': '书本',
    '📎': '回形针',
    '🧠': '大脑',
    '⚡️': '闪电',
    '☕️': '咖啡',
    '🚀': '火箭',
    '🌿': '叶子',
    '→': '右箭头',
    '•': '项目符号',
    '★': '黑星',
    '§': '节号',
    '¶': '段落号',
    '†': '匕首号',
    '‡': '双匕首号',
    '©': '版权符号',
    '®': '注册商标',
    '™': '商标符号',
    '←': '左箭头',
    '↑': '上箭头',
    '↓': '下箭头',
    '↔': '左右箭头',
    '↕': '上下箭头',
    '⇒': '推出箭头',
    '⇐': '反向推出箭头',
    '⇔': '双向推出箭头',
    '↗': '右上箭头',
    '↘': '右下箭头',
    '↙': '左下箭头',
    '↖': '左上箭头',
    '⟶': '长右箭头',
    '⟵': '长左箭头',
    '⟷': '长双向箭头',
  },
} as const;

export const MATH_SYMBOL_CATEGORIES = [
  {
    name: 'Greek Letters',
    symbols: [
      { latex: '\\alpha', display: 'α', name: 'alpha' },
      { latex: '\\beta', display: 'β', name: 'beta' },
      { latex: '\\gamma', display: 'γ', name: 'gamma' },
      { latex: '\\delta', display: 'δ', name: 'delta' },
      { latex: '\\epsilon', display: 'ε', name: 'epsilon' },
      { latex: '\\zeta', display: 'ζ', name: 'zeta' },
      { latex: '\\eta', display: 'η', name: 'eta' },
      { latex: '\\theta', display: 'θ', name: 'theta' },
      { latex: '\\lambda', display: 'λ', name: 'lambda' },
      { latex: '\\mu', display: 'μ', name: 'mu' },
      { latex: '\\nu', display: 'ν', name: 'nu' },
      { latex: '\\xi', display: 'ξ', name: 'xi' },
      { latex: '\\pi', display: 'π', name: 'pi' },
      { latex: '\\rho', display: 'ρ', name: 'rho' },
      { latex: '\\sigma', display: 'σ', name: 'sigma' },
      { latex: '\\tau', display: 'τ', name: 'tau' },
      { latex: '\\phi', display: 'φ', name: 'phi' },
      { latex: '\\psi', display: 'ψ', name: 'psi' },
      { latex: '\\omega', display: 'ω', name: 'omega' },
      { latex: '\\Gamma', display: 'Γ', name: 'Gamma' },
      { latex: '\\Delta', display: 'Δ', name: 'Delta' },
      { latex: '\\Theta', display: 'Θ', name: 'Theta' },
      { latex: '\\Lambda', display: 'Λ', name: 'Lambda' },
      { latex: '\\Sigma', display: 'Σ', name: 'Sigma' },
      { latex: '\\Phi', display: 'Φ', name: 'Phi' },
      { latex: '\\Psi', display: 'Ψ', name: 'Psi' },
      { latex: '\\Omega', display: 'Ω', name: 'Omega' },
    ],
  },
  {
    name: 'Operators',
    symbols: [
      { latex: '\\sum', display: '∑', name: 'sum' },
      { latex: '\\prod', display: '∏', name: 'product' },
      { latex: '\\int', display: '∫', name: 'integral' },
      { latex: '\\oint', display: '∮', name: 'contour integral' },
      { latex: '\\partial', display: '∂', name: 'partial' },
      { latex: '\\nabla', display: '∇', name: 'nabla' },
      { latex: '\\pm', display: '±', name: 'plus-minus' },
      { latex: '\\mp', display: '∓', name: 'minus-plus' },
      { latex: '\\times', display: '×', name: 'times' },
      { latex: '\\div', display: '÷', name: 'divide' },
      { latex: '\\cdot', display: '·', name: 'dot' },
      { latex: '\\circ', display: '∘', name: 'circle' },
      { latex: '\\sqrt{}', display: '√', name: 'sqrt' },
      { latex: '\\frac{}{}', display: 'a/b', name: 'fraction' },
    ],
  },
  {
    name: 'Relations',
    symbols: [
      { latex: '\\leq', display: '≤', name: 'less or equal' },
      { latex: '\\geq', display: '≥', name: 'greater or equal' },
      { latex: '\\neq', display: '≠', name: 'not equal' },
      { latex: '\\approx', display: '≈', name: 'approx' },
      { latex: '\\equiv', display: '≡', name: 'equiv' },
      { latex: '\\sim', display: '∼', name: 'similar' },
      { latex: '\\propto', display: '∝', name: 'proportional' },
      { latex: '\\in', display: '∈', name: 'in' },
      { latex: '\\notin', display: '∉', name: 'not in' },
      { latex: '\\ll', display: '≪', name: 'much less' },
      { latex: '\\gg', display: '≫', name: 'much greater' },
      { latex: '\\subset', display: '⊂', name: 'subset' },
      { latex: '\\supset', display: '⊃', name: 'superset' },
      { latex: '\\cap', display: '∩', name: 'intersection' },
      { latex: '\\cup', display: '∪', name: 'union' },
    ],
  },
  {
    name: 'Arrows',
    symbols: [
      { latex: '\\rightarrow', display: '→', name: 'right arrow' },
      { latex: '\\leftarrow', display: '←', name: 'left arrow' },
      { latex: '\\leftrightarrow', display: '↔', name: 'left-right arrow' },
      { latex: '\\Rightarrow', display: '⇒', name: 'implies' },
      { latex: '\\Leftarrow', display: '⇐', name: 'implied by' },
      { latex: '\\Leftrightarrow', display: '⇔', name: 'iff' },
      { latex: '\\uparrow', display: '↑', name: 'up arrow' },
      { latex: '\\downarrow', display: '↓', name: 'down arrow' },
      { latex: '\\mapsto', display: '↦', name: 'maps to' },
    ],
  },
  {
    name: 'Misc',
    symbols: [
      { latex: '\\infty', display: '∞', name: 'infinity' },
      { latex: '\\forall', display: '∀', name: 'for all' },
      { latex: '\\exists', display: '∃', name: 'exists' },
      { latex: '\\neg', display: '¬', name: 'not' },
      { latex: '\\wedge', display: '∧', name: 'and' },
      { latex: '\\vee', display: '∨', name: 'or' },
      { latex: '\\emptyset', display: '∅', name: 'empty set' },
      { latex: '\\angle', display: '∠', name: 'angle' },
      { latex: '\\perp', display: '⊥', name: 'perpendicular' },
      { latex: '\\parallel', display: '∥', name: 'parallel' },
      { latex: '\\therefore', display: '∴', name: 'therefore' },
      { latex: '\\because', display: '∵', name: 'because' },
    ],
  },
];

export const MATH_TEMPLATES = [
  { name: 'Fraction', latex: '\\frac{numerator}{denominator}', description: 'a/b' },
  { name: 'Square Root', latex: '\\sqrt{x}', description: '√x' },
  { name: 'N-th Root', latex: '\\sqrt[n]{x}', description: 'n√x' },
  { name: 'Power', latex: 'x^{n}', description: 'x^n' },
  { name: 'Subscript', latex: 'x_{i}', description: 'x_i' },
  { name: 'Sum', latex: '\\sum_{i=1}^{n} x_i', description: 'Σ x_i' },
  { name: 'Product', latex: '\\prod_{i=1}^{n} x_i', description: 'Π x_i' },
  { name: 'Integral', latex: '\\int_{a}^{b} f(x)\\,dx', description: '∫ f(x)dx' },
  { name: 'Limit', latex: '\\lim_{x \\to \\infty} f(x)', description: 'lim f(x)' },
  {
    name: 'Matrix 2x2',
    latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}',
    description: '2×2 matrix',
  },
  {
    name: 'Matrix 3x3',
    latex: '\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix}',
    description: '3×3 matrix',
  },
  {
    name: 'Cases',
    latex: '\\begin{cases} x & \\text{if } x \\geq 0 \\\\ -x & \\text{if } x < 0 \\end{cases}',
    description: 'piecewise',
  },
  { name: 'Binomial', latex: '\\binom{n}{k}', description: 'C(n,k)' },
  { name: 'Derivative', latex: '\\frac{df}{dx}', description: 'df/dx' },
  {
    name: 'Partial Derivative',
    latex: '\\frac{\\partial f}{\\partial x}',
    description: '∂f/∂x',
  },
];

export const AI_SYSTEM_PROMPT =
  'You are AsterNote, a concise writing assistant for Markdown authors. Return clean prose only.';

export const QUICK_ACTION_PROMPTS = {
  polish:
    'Polish the selected text for clarity and flow. Keep the original meaning. Return only the revised text.',
  summarize:
    'Summarize the selected text into a compact, accurate version. Return only the summary.',
  translate:
    'Translate the selected text into polished English. Return only the translation.',
  continue:
    'Continue the draft in a matching tone and structure. Return only the next passage.',
} as const;
