import type { UILanguage } from '../electron';

const UI_TEXT = {
  en: {
    common: {
      cancel: 'Cancel',
      save: 'Save',
      reset: 'Reset',
      close: 'Close',
      add: 'Add',
      remove: 'Remove',
      enabled: 'Enabled',
      default: 'Default',
      test: 'Test',
      testing: 'Testing…',
      tools: 'Tools',
      preferences: 'Preferences',
      saved: 'Saved',
      unsavedChanges: 'Unsaved changes',
      rich: 'Rich',
      source: 'Source',
      untitled: 'Untitled',
      notAvailable: 'Not available',
      notSavedYet: 'Not saved yet',
      noRecentFiles: 'No Recent Files',
      webResult: 'Web result',
    },
    toolbar: {
      openFile: 'Open file',
      save: 'Save',
      undo: 'Undo',
      redo: 'Redo',
      heading1: 'Heading 1',
      heading2: 'Heading 2',
      heading3: 'Heading 3',
      bold: 'Bold',
      italic: 'Italic',
      quote: 'Quote',
      code: 'Code',
      bulletList: 'Bullet list',
      orderedList: 'Ordered list',
      emoji: 'Emoji',
      link: 'Link',
      image: 'Image',
      table: 'Table',
      rule: 'Rule',
      math: 'Math',
      toggleSource: 'Toggle source mode',
      toggleTerminal: 'Toggle terminal',
    },
    tabs: {
      closeTab: (name: string) => `Close ${name}`,
      newTab: 'New tab',
    },
    welcome: {
      badge: 'AsterNote',
      title: 'Welcome back',
      description:
        'Open a Markdown file, continue a recent draft, or start with a clean page. The right sidebar stays quiet until you need tools or AI.',
      openMarkdown: 'Open Markdown',
      newDraft: 'New Draft',
      recentFiles: 'Recent Files',
      recentEmpty: 'Recent Markdown files will appear here after you open or save them.',
      quickStart: 'Quick Start',
      step1Title: '1. Write in rich text or source mode',
      step1Body: 'Use the top toolbar to switch views and insert Markdown structure.',
      step2Title: '2. Open Tools only when needed',
      step2Body: 'Outline, info, find, and syntax help live in the right sidebar. Emoji and math stay in the top toolbar.',
      step3Title: '3. Ask AI with fresh context',
      step3Body: 'Toggle Web inside the AI panel when you need fresh search results.',
    },
    sidebar: {
      outline: 'Outline',
      info: 'Info',
      find: 'Find',
      syntax: 'Syntax',
      resizeSidebar: 'Resize sidebar',
      structure: 'Structure',
      addHeadings: 'Add headings to build an outline.',
      documentInfo: 'Document Info',
      words: 'Words',
      chars: 'Chars',
      noSpaces: 'No spaces',
      paragraphs: 'Paragraphs',
      headings: 'Headings',
      images: 'Images',
      name: 'Name',
      path: 'Path',
      mode: 'Mode',
      status: 'Status',
      modified: 'Modified',
      findReplace: 'Find & Replace',
      findLabel: 'Find',
      findPlaceholder: 'Search the current file',
      replaceLabel: 'Replace',
      replacePlaceholder: 'Replacement text',
      replaceSelection: 'Replace Selection',
      replaceAll: 'Replace All',
      replaceHelp:
        'Replace acts on the active file. Selection replacement uses the current cursor or selection.',
      markdownCheatsheet: 'Markdown Cheatsheet',
      toolsRail: 'Tools',
      aiRail: 'AI',
      preferencesRail: 'Preferences',
    },
    ai: {
      newSession: 'New session',
      clearCurrentSession: 'Clear current session',
      workspace: 'Workspace',
      assistantName: 'AsterNote Assistant',
      selectionAttached: 'Selection attached',
      wholeDraftContext: 'Whole draft context',
      webSearchEnabled: 'Web search on',
      documentOnlyReplies: 'Document-only replies',
      memoryOn: (count: number) => `Memory on · ${count} notes`,
      memoryOff: 'Memory off',
      polish: 'Polish',
      summarize: 'Summarize',
      translate: 'Translate',
      continue: 'Continue',
      history: 'Chat history',
      emptyTitle: 'New session',
      emptyBody:
        'Work with your assistant to revise the current draft, translate passages, or keep writing with session memory.',
      assistant: 'Assistant',
      you: 'You',
      webSearchSuffix: ' · Web Search',
      replaceSelection: 'Replace selection',
      insertAtCursor: 'Insert at cursor',
      prompt: 'Prompt',
      promptPlaceholder: 'Ask about this draft, a paragraph, or the current selection...',
      noEnabledProviders: 'No model configured',
      web: 'Web',
      toggleWebSearch: 'Toggle web search',
      configureWebSearchFirst: 'Configure a search provider first',
      aiSettings: 'AI settings',
      selectionFooter: 'Replies can replace the current selection or insert after the cursor.',
      noSelectionFooter: 'No selection detected. The assistant will use the whole draft as context.',
      clearMemory: 'Clear memory',
      sendPrompt: 'Send prompt',
      thinking: 'Thinking',
      contextSelection: 'Use the current selection as context',
      contextDraft: 'Use the whole draft as context',
      memoryStatus: 'Memory status',
      quickActions: 'Quick actions',
    },
    settings: {
      title: 'Preferences',
      subtitle: 'Desktop defaults, OpenAI-compatible model providers, and web search providers live here.',
      editor: 'Editor',
      theme: 'Theme',
      fontSize: 'Font size',
      uiLanguage: 'UI language',
      defaultView: 'Default view',
      richText: 'Rich text',
      sourceMode: 'Source',
      searchInChatTitle: 'Search in Chat',
      searchInChatBody:
        'Choose a search API here, then use the Web toggle inside the AI sidebar whenever you want fresh context.',
      aiProviders: 'AI Providers',
      aiProvidersBody: 'Any OpenAI-compatible /chat/completions endpoint can be used here.',
      noConfiguredProviders: 'No configured providers yet. Click Add when you want to connect another model.',
      addProvider: 'Add',
      customProvider: 'OpenAI-Compatible Provider',
      providerName: 'Name',
      providerNamePlaceholder: 'OpenAI or compatible service',
      baseUrl: 'Base URL',
      baseUrlPlaceholder: 'https://api.openai.com/v1',
      model: 'Model',
      modelPlaceholder: 'gpt-4.1-mini',
      apiKey: 'API Key',
      storedKey: 'Stored key',
      pasteApiKey: 'Paste API key',
      testConnection: 'Test',
      testingConnection: 'Testing…',
      removeProvider: 'Remove',
      webSearch: 'Web Search',
      webSearchBody: 'Use Brave, Tavily, Perplexity, or Google search from the AI panel.',
      searchProvider: 'Search provider',
      searchProviderHintBrave: 'Brave only needs the endpoint, API key, and result count here.',
      searchProviderHintTavily: 'Tavily only needs the endpoint, API key, and result count here.',
      searchProviderHintPerplexity: 'Perplexity only needs the endpoint, API key, and result count here.',
      searchProviderHintGoogle:
        'Google needs the endpoint, API key, result count, and Search engine ID here.',
      testSearch: 'Test Search',
      testingSearch: 'Testing…',
      resultCount: 'Result count',
      searchEngineId: 'Search engine ID',
      pasteSearchKey: 'Paste search API key',
      aiMemory: 'AI Memory',
      enableMemory: 'Enable long-term memory for AI collaboration',
      memoryBody:
        'AsterNote keeps stable preferences and workflow signals locally on this device. Session history remains intact unless you clear it.',
      clearLongTermMemory: 'Clear Long-Term Memory',
      reset: 'Reset',
      savePreferences: 'Save Preferences',
      savingPreferences: 'Saving…',
      english: 'English',
      chinese: '简体中文',
    },
    dialogs: {
      inputSingleLineHint: 'Enter a value to insert into the current document.',
      inputMultiLineHint: 'Paste or type LaTeX, then insert it into the current document.',
      closeInput: 'Close input dialog',
      mathComposerHint: 'Compose LaTeX with symbols and templates, then insert it into the current document.',
      closeMathComposer: 'Close math composer',
    },
    math: {
      composer: 'Math Composer',
      block: 'Block',
      inline: 'Inline',
      latex: 'LaTeX',
      previewEmpty: 'Type LaTeX above to preview the equation.',
      insertEquation: 'Insert Equation',
      insertInlineFormula: 'Insert Inline Formula',
      insertFormulaBlock: 'Insert Formula Block',
      symbols: 'Symbols',
      templates: 'Templates',
      inThisDocument: 'In This Document',
      tableOptions: 'Table options',
      tableInsertRowAbove: 'Insert row above',
      tableInsertRowBelow: 'Insert row below',
      tableInsertColumnLeft: 'Insert column left',
      tableInsertColumnRight: 'Insert column right',
      tableMergeCells: 'Merge cells',
      tableSplitCell: 'Split cell',
      tableInsertLineBreak: 'Insert line break',
      tableToggleHeaderRow: 'Toggle header row',
      tableToggleHeaderColumn: 'Toggle header column',
      tableDeleteRow: 'Delete row',
      tableDeleteColumn: 'Delete column',
      tableDeleteTable: 'Delete table',
      contextRowsColumns: 'Rows / Columns',
      contextCells: 'Cells',
      contextHeaders: 'Headers',
      contextDelete: 'Delete',
      contextInsertRowAbove: 'Insert Row Above',
      contextInsertRowBelow: 'Insert Row Below',
      contextInsertColumnLeft: 'Insert Column Left',
      contextInsertColumnRight: 'Insert Column Right',
      contextMergeCells: 'Merge Cells',
      contextSplitCell: 'Split Cell',
      contextInsertLineBreak: 'Insert Line Break',
      contextToggleHeaderRow: 'Toggle Header Row',
      contextToggleHeaderColumn: 'Toggle Header Column',
      contextDeleteRow: 'Delete Row',
      contextDeleteColumn: 'Delete Column',
      contextDeleteTable: 'Delete Table',
      symbolCategories: {
        'Greek Letters': 'Greek Letters',
        Operators: 'Operators',
        Relations: 'Relations',
        Arrows: 'Arrows',
        Misc: 'Misc',
      },
      templateNames: {
        Fraction: 'Fraction',
        'Square Root': 'Square Root',
        'N-th Root': 'N-th Root',
        Power: 'Power',
        Subscript: 'Subscript',
        Sum: 'Sum',
        Product: 'Product',
        Integral: 'Integral',
        Limit: 'Limit',
        'Matrix 2x2': 'Matrix 2x2',
        'Matrix 3x3': 'Matrix 3x3',
        Cases: 'Cases',
        Binomial: 'Binomial',
        Derivative: 'Derivative',
        'Partial Derivative': 'Partial Derivative',
      },
      templateDescriptions: {
        '2×2 matrix': '2×2 matrix',
        '3×3 matrix': '3×3 matrix',
        piecewise: 'piecewise',
      },
    },
    codeBlock: {
      plainText: 'Plain text',
      line: 'Line',
      paper: 'Paper',
      slate: 'Slate',
      midnight: 'Midnight',
    },
    contextMenu: {
      bold: 'Bold',
      italic: 'Italic',
      inlineCode: 'Inline Code',
      link: 'Link',
      enterUrl: 'Enter URL',
      bulletList: 'Bullet List',
      numberedList: 'Numbered List',
      quote: 'Quote',
      codeBlock: 'Code Block',
      insertTable: 'Insert Table',
    },
    terminal: {
      launchingShell: 'Launching shell...',
      preparingShell: 'Preparing shell…',
      restartTerminal: 'Restart terminal',
      closeTerminal: 'Close terminal',
      exitedWithCode: (code: number, signal?: string | null) =>
        `[AsterNote] terminal exited with code ${code}${signal ? ` (${signal})` : ''}`,
    },
    app: {
      untitledBase: 'Untitled',
      browserFallbackNote:
        'Browser fallback mode. File dialogs, desktop events, terminal sessions, and provider-backed AI are disabled here.',
      clearMemoryConfirm: 'Clear AsterNote long-term AI memory for this workspace?',
      unableToOpenRecentFile: 'Unable to open recent file.',
      closeWithoutSaving: (name: string) => `Close ${name} without saving?`,
      saveBeforeAssetInsert: 'Save the document first so AsterNote can write a relative asset path.',
      unsupportedDropTypes: (items: string) => `Unsupported drop types: ${items}`,
      insertLinkTitle: 'Insert Link',
      destinationUrl: 'Destination URL',
      insertLink: 'Insert Link',
      insertInlineFormula: 'Insert Inline Formula',
      insertFormulaBlock: 'Insert Formula Block',
      noTextForAction: 'There is no text available for this action.',
      aiRequestFailed: 'AI request failed.',
      resetPreferencesConfirm: 'Reset AsterNote preferences to defaults?',
      quickStartHelp:
        'Open or create a Markdown file, write in rich or source mode, then use the right sidebar for tools and AI. The terminal button opens a shell at the current file folder.',
      shortcutsHelp:
        'Common shortcuts: Cmd/Ctrl+N new, O open, S save, Shift+S save as, J terminal, Shift+A AI panel, Shift+M source mode.',
      heading: 'Heading',
      quote: 'Quote',
      item: 'Item',
      columnA: 'Column A',
      columnB: 'Column B',
      value: 'Value',
      text: 'text',
      link: 'link',
      imageAlt: 'image',
      untitledFile: 'Untitled.md',
    },
    syntax: {
      categories: {
        Headings: 'Headings',
        Text: 'Text',
        Lists: 'Lists',
        'Links & Media': 'Links & Media',
        Blocks: 'Blocks',
        Tables: 'Tables',
        Notes: 'Notes',
      },
      descriptions: {
        'H1 heading': 'H1 heading',
        'H2 heading': 'H2 heading',
        'H3 heading': 'H3 heading',
        'H4 heading': 'H4 heading',
        'H5 heading': 'H5 heading',
        'H6 heading': 'H6 heading',
        'Bold text': 'Bold text',
        'Italic text': 'Italic text',
        'Bold + italic': 'Bold + italic',
        Strikethrough: 'Strikethrough',
        'Inline code': 'Inline code',
        'Inline HTML highlight': 'Inline HTML highlight',
        'Unordered list': 'Unordered list',
        'Ordered list': 'Ordered list',
        'Task list': 'Task list',
        'Completed task': 'Completed task',
        'Nested list item': 'Nested list item',
        Link: 'Link',
        Image: 'Image',
        Autolink: 'Autolink',
        'Reference link': 'Reference link',
        'Reference target': 'Reference target',
        Blockquote: 'Blockquote',
        'Multi-line quote': 'Multi-line quote',
        'Horizontal rule': 'Horizontal rule',
        'Code fence': 'Code fence',
        'Math block': 'Math block',
        'HTML comment': 'HTML comment',
        'Table header': 'Table header',
        'Table separator': 'Table separator',
        'Left / right alignment': 'Left / right alignment',
        'Table row': 'Table row',
        'Inline math': 'Inline math',
        'Footnote ref': 'Footnote ref',
        'Footnote body': 'Footnote body',
        'Escape markdown token': 'Escape markdown token',
      },
    },
  },
  'zh-CN': {
    common: {
      cancel: '取消',
      save: '保存',
      reset: '重置',
      close: '关闭',
      add: '新增',
      remove: '移除',
      enabled: '启用',
      default: '默认',
      test: '测试',
      testing: '测试中…',
      tools: '工具',
      preferences: '偏好设置',
      saved: '已保存',
      unsavedChanges: '未保存修改',
      rich: '富文本',
      source: '源码',
      untitled: '未命名',
      notAvailable: '不可用',
      notSavedYet: '尚未保存',
      noRecentFiles: '没有最近文件',
      webResult: '网页结果',
    },
    toolbar: {
      openFile: '打开文件',
      save: '保存',
      undo: '撤销',
      redo: '重做',
      heading1: '一级标题',
      heading2: '二级标题',
      heading3: '三级标题',
      bold: '加粗',
      italic: '斜体',
      quote: '引用',
      code: '代码',
      bulletList: '无序列表',
      orderedList: '有序列表',
      emoji: '表情符号',
      link: '链接',
      image: '图片',
      table: '表格',
      rule: '分隔线',
      math: '公式',
      toggleSource: '切换源码模式',
      toggleTerminal: '切换终端',
    },
    tabs: {
      closeTab: (name: string) => `关闭 ${name}`,
      newTab: '新建标签',
    },
    welcome: {
      badge: 'AsterNote',
      title: '欢迎回来',
      description:
        '打开 Markdown 文件、继续最近草稿，或从空白页开始。右侧边栏会在你需要工具或 AI 时再出现。',
      openMarkdown: '打开 Markdown',
      newDraft: '新建草稿',
      recentFiles: '最近文件',
      recentEmpty: '打开或保存 Markdown 文件后，最近文件会显示在这里。',
      quickStart: '快速开始',
      step1Title: '1. 在富文本或源码模式下写作',
      step1Body: '使用顶部工具栏切换视图并插入 Markdown 结构。',
      step2Title: '2. 需要时再打开工具面板',
      step2Body: '大纲、信息、查找和语法帮助位于右侧边栏；表情和公式位于顶部工具栏。',
      step3Title: '3. 使用最新上下文提问 AI',
      step3Body: '需要最新搜索结果时，可在 AI 面板中打开联网模式。',
    },
    sidebar: {
      outline: '大纲',
      info: '信息',
      find: '查找',
      syntax: '语法',
      resizeSidebar: '调整侧栏宽度',
      structure: '文档结构',
      addHeadings: '添加标题后，这里会生成大纲。',
      documentInfo: '文档信息',
      words: '词数',
      chars: '字符',
      noSpaces: '不含空格',
      paragraphs: '段落',
      headings: '标题',
      images: '图片',
      name: '名称',
      path: '路径',
      mode: '模式',
      status: '状态',
      modified: '修改时间',
      findReplace: '查找与替换',
      findLabel: '查找',
      findPlaceholder: '搜索当前文件',
      replaceLabel: '替换',
      replacePlaceholder: '替换文本',
      replaceSelection: '替换所选内容',
      replaceAll: '全部替换',
      replaceHelp: '替换只作用于当前文件。替换所选内容会使用当前光标或选择区。',
      markdownCheatsheet: 'Markdown 速查表',
      toolsRail: '工具',
      aiRail: 'AI',
      preferencesRail: '偏好设置',
    },
    ai: {
      newSession: '新建会话',
      clearCurrentSession: '清空当前会话',
      workspace: '工作区',
      assistantName: 'AsterNote 助手',
      selectionAttached: '已附加选区',
      wholeDraftContext: '使用整篇草稿上下文',
      webSearchEnabled: '已开启联网搜索',
      documentOnlyReplies: '仅基于文档回答',
      memoryOn: (count: number) => `记忆已开启 · ${count} 条`,
      memoryOff: '记忆已关闭',
      polish: '润色',
      summarize: '总结',
      translate: '翻译',
      continue: '续写',
      history: '聊天记录',
      emptyTitle: '新建会话',
      emptyBody: '让助手帮你修改当前草稿、翻译段落，或结合会话记忆继续写作。',
      assistant: '助手',
      you: '你',
      webSearchSuffix: ' · 网页搜索',
      replaceSelection: '替换选区',
      insertAtCursor: '插入到光标处',
      prompt: '提问',
      promptPlaceholder: '询问当前草稿、某段文字或当前选区…',
      noEnabledProviders: '没有已配置模型',
      web: '联网',
      toggleWebSearch: '切换联网搜索',
      configureWebSearchFirst: '请先配置搜索提供商',
      aiSettings: 'AI 设置',
      selectionFooter: '回复可以替换当前选区，或插入到光标后。',
      noSelectionFooter: '当前没有选区，助手将使用整篇草稿作为上下文。',
      clearMemory: '清空记忆',
      sendPrompt: '发送提问',
      thinking: '思考中',
      contextSelection: '使用当前选区作为上下文',
      contextDraft: '使用整篇草稿作为上下文',
      memoryStatus: '记忆状态',
      quickActions: '快捷动作',
    },
    settings: {
      title: '偏好设置',
      subtitle: '桌面默认项、OpenAI 兼容模型提供商和搜索提供商配置都在这里。',
      editor: '编辑器',
      theme: '主题',
      fontSize: '字号',
      uiLanguage: '界面语言',
      defaultView: '默认视图',
      richText: '富文本',
      sourceMode: '源码',
      searchInChatTitle: '聊天搜索',
      searchInChatBody: '先在这里选择搜索 API，再在 AI 侧栏中按需切换联网搜索。',
      aiProviders: 'AI 提供商',
      aiProvidersBody: '这里只要求接口兼容 OpenAI 的 /chat/completions。',
      noConfiguredProviders: '当前没有已配置的提供商。需要接入新模型时，点击新增即可。',
      addProvider: '新增',
      customProvider: 'OpenAI 兼容提供商',
      providerName: '名称',
      providerNamePlaceholder: 'OpenAI 或兼容服务',
      baseUrl: 'Base URL',
      baseUrlPlaceholder: 'https://api.openai.com/v1',
      model: '模型',
      modelPlaceholder: 'gpt-4.1-mini',
      apiKey: 'API Key',
      storedKey: '已存储密钥',
      pasteApiKey: '粘贴 API Key',
      testConnection: '测试',
      testingConnection: '测试中…',
      removeProvider: '移除',
      webSearch: '联网搜索',
      webSearchBody: 'AI 面板里的联网按钮可以使用 Brave、Tavily、Perplexity 或 Google。',
      searchProvider: '搜索提供商',
      searchProviderHintBrave: 'Brave 这里只需要端点、API Key 和结果数量。',
      searchProviderHintTavily: 'Tavily 这里只需要端点、API Key 和结果数量。',
      searchProviderHintPerplexity: 'Perplexity 这里只需要端点、API Key 和结果数量。',
      searchProviderHintGoogle: 'Google 这里只需要端点、API Key、结果数量和 Search Engine ID。',
      testSearch: '测试搜索',
      testingSearch: '测试中…',
      resultCount: '结果数量',
      searchEngineId: 'Search Engine ID',
      pasteSearchKey: '粘贴搜索 API Key',
      aiMemory: 'AI 记忆',
      enableMemory: '为 AI 协作启用长期记忆',
      memoryBody: 'AsterNote 会在本机保存稳定的偏好和工作流信号。除非手动清除，会话历史会一直保留。',
      clearLongTermMemory: '清空长期记忆',
      reset: '重置',
      savePreferences: '保存偏好设置',
      savingPreferences: '保存中…',
      english: 'English',
      chinese: '简体中文',
    },
    dialogs: {
      inputSingleLineHint: '输入一个值并插入到当前文档。',
      inputMultiLineHint: '输入或粘贴 LaTeX，然后插入到当前文档。',
      closeInput: '关闭输入对话框',
      mathComposerHint: '使用符号和模板编写 LaTeX，然后插入到当前文档。',
      closeMathComposer: '关闭公式编辑器',
    },
    math: {
      composer: '公式编辑器',
      block: '块级',
      inline: '行内',
      latex: 'LaTeX',
      previewEmpty: '在上方输入 LaTeX 后，可在这里预览公式。',
      insertEquation: '插入公式',
      insertInlineFormula: '插入行内公式',
      insertFormulaBlock: '插入公式块',
      symbols: '符号',
      templates: '模板',
      inThisDocument: '当前文档中的公式',
      tableOptions: '表格选项',
      tableInsertRowAbove: '在上方插入行',
      tableInsertRowBelow: '在下方插入行',
      tableInsertColumnLeft: '在左侧插入列',
      tableInsertColumnRight: '在右侧插入列',
      tableMergeCells: '合并单元格',
      tableSplitCell: '拆分单元格',
      tableInsertLineBreak: '插入换行',
      tableToggleHeaderRow: '切换表头行',
      tableToggleHeaderColumn: '切换表头列',
      tableDeleteRow: '删除行',
      tableDeleteColumn: '删除列',
      tableDeleteTable: '删除表格',
      contextRowsColumns: '行 / 列',
      contextCells: '单元格',
      contextHeaders: '表头',
      contextDelete: '删除',
      contextInsertRowAbove: '在上方插入行',
      contextInsertRowBelow: '在下方插入行',
      contextInsertColumnLeft: '在左侧插入列',
      contextInsertColumnRight: '在右侧插入列',
      contextMergeCells: '合并单元格',
      contextSplitCell: '拆分单元格',
      contextInsertLineBreak: '插入换行',
      contextToggleHeaderRow: '切换表头行',
      contextToggleHeaderColumn: '切换表头列',
      contextDeleteRow: '删除行',
      contextDeleteColumn: '删除列',
      contextDeleteTable: '删除表格',
      symbolCategories: {
        'Greek Letters': '希腊字母',
        Operators: '运算符',
        Relations: '关系符',
        Arrows: '箭头',
        Misc: '其他',
      },
      templateNames: {
        Fraction: '分数',
        'Square Root': '平方根',
        'N-th Root': 'n 次根',
        Power: '幂',
        Subscript: '下标',
        Sum: '求和',
        Product: '求积',
        Integral: '积分',
        Limit: '极限',
        'Matrix 2x2': '2×2 矩阵',
        'Matrix 3x3': '3×3 矩阵',
        Cases: '分段函数',
        Binomial: '二项式系数',
        Derivative: '导数',
        'Partial Derivative': '偏导数',
      },
      templateDescriptions: {
        '2×2 matrix': '2×2 矩阵',
        '3×3 matrix': '3×3 矩阵',
        piecewise: '分段表达式',
      },
    },
    codeBlock: {
      plainText: '纯文本',
      line: '行号',
      paper: '纸张',
      slate: '石板',
      midnight: '午夜',
    },
    contextMenu: {
      bold: '加粗',
      italic: '斜体',
      inlineCode: '行内代码',
      link: '链接',
      enterUrl: '输入 URL',
      bulletList: '无序列表',
      numberedList: '有序列表',
      quote: '引用',
      codeBlock: '代码块',
      insertTable: '插入表格',
    },
    terminal: {
      launchingShell: '正在启动 Shell…',
      preparingShell: '正在准备 Shell…',
      restartTerminal: '重启终端',
      closeTerminal: '关闭终端',
      exitedWithCode: (code: number, signal?: string | null) =>
        `[AsterNote] 终端已退出，退出码 ${code}${signal ? ` (${signal})` : ''}`,
    },
    app: {
      untitledBase: '未命名',
      browserFallbackNote:
        '当前为浏览器降级模式。文件对话框、桌面事件、终端会话和接入提供商的 AI 在这里不可用。',
      clearMemoryConfirm: '要清空当前工作区的 AsterNote 长期 AI 记忆吗？',
      unableToOpenRecentFile: '无法打开最近文件。',
      closeWithoutSaving: (name: string) => `关闭 ${name} 且不保存？`,
      saveBeforeAssetInsert: '请先保存文档，这样 AsterNote 才能写入相对资源路径。',
      unsupportedDropTypes: (items: string) => `不支持的拖拽类型：${items}`,
      insertLinkTitle: '插入链接',
      destinationUrl: '目标 URL',
      insertLink: '插入链接',
      insertInlineFormula: '插入行内公式',
      insertFormulaBlock: '插入公式块',
      noTextForAction: '当前没有可用于此操作的文本。',
      aiRequestFailed: 'AI 请求失败。',
      resetPreferencesConfirm: '要将 AsterNote 偏好设置重置为默认值吗？',
      quickStartHelp:
        '打开或创建 Markdown 文件，在富文本或源码模式下写作，然后使用右侧边栏中的工具和 AI。终端按钮会在当前文件所在目录打开 Shell。',
      shortcutsHelp:
        '常用快捷键：Cmd/Ctrl+N 新建，O 打开，S 保存，Shift+S 另存为，J 终端，Shift+A AI 面板，Shift+M 源码模式。',
      heading: '标题',
      quote: '引用',
      item: '项目',
      columnA: '列 A',
      columnB: '列 B',
      value: '值',
      text: '文本',
      link: '链接',
      imageAlt: '图片',
      untitledFile: '未命名.md',
    },
    syntax: {
      categories: {
        Headings: '标题',
        Text: '文本',
        Lists: '列表',
        'Links & Media': '链接与媒体',
        Blocks: '块元素',
        Tables: '表格',
        Notes: '补充',
      },
      descriptions: {
        'H1 heading': '一级标题',
        'H2 heading': '二级标题',
        'H3 heading': '三级标题',
        'H4 heading': '四级标题',
        'H5 heading': '五级标题',
        'H6 heading': '六级标题',
        'Bold text': '加粗文本',
        'Italic text': '斜体文本',
        'Bold + italic': '加粗 + 斜体',
        Strikethrough: '删除线',
        'Inline code': '行内代码',
        'Inline HTML highlight': '行内 HTML 高亮',
        'Unordered list': '无序列表',
        'Ordered list': '有序列表',
        'Task list': '任务列表',
        'Completed task': '已完成任务',
        'Nested list item': '嵌套列表项',
        Link: '链接',
        Image: '图片',
        Autolink: '自动链接',
        'Reference link': '引用式链接',
        'Reference target': '引用目标',
        Blockquote: '引用块',
        'Multi-line quote': '多行引用',
        'Horizontal rule': '分隔线',
        'Code fence': '代码围栏',
        'Math block': '公式块',
        'HTML comment': 'HTML 注释',
        'Table header': '表头',
        'Table separator': '表格分隔行',
        'Left / right alignment': '左 / 右对齐',
        'Table row': '表格行',
        'Inline math': '行内公式',
        'Footnote ref': '脚注引用',
        'Footnote body': '脚注内容',
        'Escape markdown token': '转义 Markdown 标记',
      },
    },
  },
} as const;

export function resolveUiLanguage(language?: UILanguage | null): UILanguage {
  return language === 'zh-CN' ? 'zh-CN' : 'en';
}

export function getUiText(language?: UILanguage | null) {
  return UI_TEXT[resolveUiLanguage(language)];
}

export function getDocumentUiLanguage(): UILanguage {
  if (typeof document === 'undefined') {
    return 'en';
  }
  return resolveUiLanguage((document.documentElement.dataset.uiLanguage as UILanguage | undefined) || 'en');
}
